export const ADMIN_PROFESSORS_MOCK_DATA = [
  {
    professorNo: 1,
    professorName: '김은진',
    position: '교수 (학과주임)',
    major: '미술치료전공',
    email: 'eunjin49@hanyang.ac.kr',
    tel: '031-400-5107',
    files: {
      filesNo: 25,
      url: '/images/intro/professors/professors-01.webp',
    },
  },
  {
    professorNo: 2,
    professorName: '옥금자',
    position: '자문위원',
    major: '',
    email: '',
    tel: '',
    files: {
      filesNo: 26,
      url: '/images/intro/professors/professors-02.webp',
    },
  },
  {
    professorNo: 3,
    professorName: '김현미',
    position: '교수',
    major: '미술치료전공',
    email: 'studio505@hanyang.ac.kr',
    tel: '',
    files: {
      filesNo: 27,
      url: '/images/intro/professors/professors-03.webp',
    },
  },
  {
    professorNo: 4,
    professorName: '박성은',
    position: '교수',
    major: '미술치료전공',
    email: 'hyeyu@hanyang.ac.kr',
    tel: '',
    files: {
      filesNo: 28,
      url: '/images/intro/professors/professors-04.webp',
    },
  },
  {
    professorNo: 5,
    professorName: '이현주',
    position: '교수',
    major: '미술치료전공',
    email: 'lhjlhj529@hanyang.ac.kr',
    tel: '',
    files: {
      filesNo: 29,
      url: '/images/intro/professors/professors-05.webp',
    },
  },
  {
    professorNo: 6,
    professorName: '한영희',
    position: '교수',
    major: '예술치료전공',
    email: 'yhee711@hanyang.ac.kr',
    tel: '',
    files: {
      filesNo: 30,
      url: '/images/intro/professors/professors-06.webp',
    },
  },
  {
    professorNo: 7,
    professorName: '허성호',
    position: '교수',
    major: '심리학전공',
    email: 'powerrcy@hanyang.ac.kr',
    tel: '',
    files: {
      filesNo: 31,
      url: '/images/intro/professors/professors-07.webp',
    },
  },
];
