export const ADMIN_USERS_MOCK_DATA = {
  content: [
    {
      userNo: 1,
      userId: 'test1',
      email: 'test1@gmail.com',
      userName: '테스트1',
      studentNo: '',
      role: 'USER',
      userStatus: 'ACTIVE',
      signinTimestamp: '2025-05-14T19:47:46.137+00:00',
      signoutTimestamp: '',
      bannedTimestamp: '',
      cause: '',
    },
    {
      userNo: 2,
      userId: 'test2',
      email: 'test2@gmail.com',
      userName: '테스트2',
      studentNo: '',
      role: 'USER',
      userStatus: 'ACTIVE',
      signinTimestamp: '2025-05-14T19:47:46.137+00:00',
      signoutTimestamp: '',
      bannedTimestamp: '',
      cause: '',
    },
    {
      userNo: 3,
      userId: 'test3',
      email: 'test3@gmail.com',
      userName: '테스트3',
      studentNo: '',
      role: 'USER',
      userStatus: 'ACTIVE',
      signinTimestamp: '2025-05-14T19:47:46.137+00:00',
      signoutTimestamp: '',
      bannedTimestamp: '',
      cause: '',
    },
    {
      userNo: 4,
      userId: 'test4',
      email: 'test4@gmail.com',
      userName: '강송희',
      studentNo: 1234567800,
      role: 'ARTIST',
      userStatus: 'ACTIVE',
      signinTimestamp: '2025-05-14T19:47:46.137+00:00',
      signoutTimestamp: '',
      bannedTimestamp: '',
      cause: '',
    },
    {
      userNo: 5,
      userId: 'test5',
      email: 'test5@gmail.com',
      userName: '구교희',
      studentNo: 8765432100,
      role: 'ARTIST',
      userStatus: 'ACTIVE',
      signinTimestamp: '2025-05-14T19:47:46.137+00:00',
      signoutTimestamp: '',
      bannedTimestamp: '',
      cause: '',
    },
    {
      userNo: 6,
      userId: 'test6',
      email: 'test1@gmail.com',
      userName: '테스트6',
      studentNo: '',
      role: 'USER',
      userStatus: 'ACTIVE',
      signinTimestamp: '2025-05-14T19:47:46.137+00:00',
      signoutTimestamp: '',
      bannedTimestamp: '',
      cause: '',
    },
    {
      userNo: 7,
      userId: 'test7',
      email: 'test2@gmail.com',
      userName: '테스트7',
      studentNo: '',
      role: 'USER',
      userStatus: 'ACTIVE',
      signinTimestamp: '2025-05-14T19:47:46.137+00:00',
      signoutTimestamp: '',
      bannedTimestamp: '',
      cause: '',
    },
    {
      userNo: 8,
      userId: 'test8',
      email: 'test3@gmail.com',
      userName: '테스트8',
      studentNo: '',
      role: 'USER',
      userStatus: 'ACTIVE',
      signinTimestamp: '2025-05-14T19:47:46.137+00:00',
      signoutTimestamp: '',
      bannedTimestamp: '',
      cause: '',
    },
    {
      userNo: 9,
      userId: 'test9',
      email: 'test9@gmail.com',
      userName: '테스트9',
      studentNo: '',
      role: 'USER',
      userStatus: 'ACTIVE',
      signinTimestamp: '2025-05-14T19:47:46.137+00:00',
      signoutTimestamp: '',
      bannedTimestamp: '',
      cause: '',
    },
    {
      userNo: 10,
      userId: 'test10',
      email: 'test10@gmail.com',
      userName: '테스트10',
      studentNo: '',
      role: 'USER',
      userStatus: 'ACTIVE',
      signinTimestamp: '2025-05-14T19:47:46.137+00:00',
      signoutTimestamp: '',
      bannedTimestamp: '',
      cause: '',
    },
    {
      userNo: 11,
      userId: 'test11',
      email: 'test10@gmail.com',
      userName: '테스트11',
      studentNo: '',
      role: 'USER',
      userStatus: 'ACTIVE',
      signinTimestamp: '2025-05-14T19:47:46.137+00:00',
      signoutTimestamp: '',
      bannedTimestamp: '',
      cause: '',
    },
    {
      userNo: 12,
      userId: 'test12',
      email: 'test10@gmail.com',
      userName: '테스트12',
      studentNo: '',
      role: 'USER',
      userStatus: 'ACTIVE',
      signinTimestamp: '2025-05-14T19:47:46.137+00:00',
      signoutTimestamp: '',
      bannedTimestamp: '',
      cause: '',
    },
    {
      userNo: 13,
      userId: 'test13',
      email: 'test10@gmail.com',
      userName: '테스트13',
      studentNo: '',
      role: 'USER',
      userStatus: 'ACTIVE',
      signinTimestamp: '2025-05-14T19:47:46.137+00:00',
      signoutTimestamp: '',
      bannedTimestamp: '',
      cause: '',
    },
    {
      userNo: 14,
      userId: 'test14',
      email: 'test10@gmail.com',
      userName: '테스트14',
      studentNo: '',
      role: 'USER',
      userStatus: 'ACTIVE',
      signinTimestamp: '2025-05-14T19:47:46.137+00:00',
      signoutTimestamp: '',
      bannedTimestamp: '',
      cause: '',
    },
    {
      userNo: 15,
      userId: 'test15',
      email: 'test10@gmail.com',
      userName: '테스트15',
      studentNo: '',
      role: 'USER',
      userStatus: 'ACTIVE',
      signinTimestamp: '2025-05-14T19:47:46.137+00:00',
      signoutTimestamp: '',
      bannedTimestamp: '',
      cause: '',
    },
  ],
  lastId: 2,
  hasNext: false,
};
