export const NOTICE_MOCK_DATA = {
  content: [
    {
      noticeNo: 1,
      category: '중요',
      title: '서비스 점검 안내',
      content: '5월 25일 02:00~04:00 서비스 점검이 진행됩니다.',
      writer: '관리자',
      createdAt: '2025-05-21T10:00:00',
    },
    {
      noticeNo: 2,
      category: '일반',
      title: '신규 기능 추가',
      content: '게시판에 이미지 첨부 기능이 추가되었습니다.',
      writer: '관리자',
      createdAt: '2025-05-22T09:30:00',
    },
    {
      noticeNo: 3,
      category: '이벤트',
      title: '이벤트 안내',
      content: '회원가입 이벤트가 6월 1일부터 시작됩니다.',
      writer: '관리자',
      createdAt: '2025-05-23T14:00:00',
    },
    {
      noticeNo: 4,
      category: '중요',
      title: '개인정보 처리방침 변경',
      content: '개인정보 처리방침이 6월 1일자로 변경됩니다.',
      writer: '관리자',
      createdAt: '2025-05-24T11:00:00',
    },
    {
      noticeNo: 5,
      category: '일반',
      title: 'FAQ 업데이트',
      content: '자주 묻는 질문(FAQ)이 업데이트되었습니다.',
      writer: '관리자',
      createdAt: '2025-05-25T08:00:00',
    },
    {
      noticeNo: 6,
      category: '중요',
      title: '보안 점검 안내',
      content: '정기 보안 점검이 6월 5일에 진행됩니다.',
      writer: '관리자',
      createdAt: '2025-05-26T10:00:00',
    },
    {
      noticeNo: 7,
      category: '일반',
      title: '모바일 앱 출시',
      content: '모바일 앱이 정식 출시되었습니다.',
      writer: '관리자',
      createdAt: '2025-05-27T13:00:00',
    },
    {
      noticeNo: 8,
      category: '이벤트',
      title: '출석체크 이벤트',
      content: '매일 출석체크 시 포인트를 드립니다.',
      writer: '관리자',
      createdAt: '2025-05-28T09:00:00',
    },
    {
      noticeNo: 9,
      category: '중요',
      title: '서비스 장애 안내',
      content: '5월 20일 발생한 장애에 대해 사과드립니다.',
      writer: '관리자',
      createdAt: '2025-05-29T15:00:00',
    },
    {
      noticeNo: 10,
      category: '일반',
      title: '커뮤니티 오픈',
      content: '새로운 커뮤니티 게시판이 오픈되었습니다.',
      writer: '관리자',
      createdAt: '2025-05-30T10:00:00',
    },
    {
      noticeNo: 11,
      category: '이벤트',
      title: '리뷰 이벤트',
      content: '리뷰 작성 시 추첨을 통해 상품을 드립니다.',
      writer: '관리자',
      createdAt: '2025-05-31T12:00:00',
    },
    {
      noticeNo: 12,
      category: '중요',
      title: '약관 변경 안내',
      content: '이용약관이 6월 10일자로 변경됩니다.',
      writer: '관리자',
      createdAt: '2025-06-01T09:00:00',
    },
    {
      noticeNo: 13,
      category: '일반',
      title: '고객센터 운영시간 변경',
      content: '고객센터 운영시간이 09:00~18:00로 변경됩니다.',
      writer: '관리자',
      createdAt: '2025-06-02T10:00:00',
    },
  ],
  page: 0,
  size: 5,
  totalElements: 13,
  totalPages: 3,
};
