export const PROFESSORS = [
  {
    name: '김은진',
    position: '교수 (학과주임)',
    major: '미술치료전공',
    email: 'eunjin49@hanyang.ac.kr',
    phone: '031-400-5107',
    image: '/images/intro/professors/professors-01.webp',
  },
  {
    name: '옥금자',
    position: '자문위원',
    major: '',
    email: '',
    phone: '',
    image: '/images/intro/professors/professors-02.webp',
  },
  {
    name: '김현미',
    position: '교수',
    major: '미술치료전공',
    email: 'studio505@hanyang.ac.kr',
    phone: '',
    image: '/images/intro/professors/professors-03.webp',
  },
  {
    name: '박성은',
    position: '교수',
    major: '미술치료전공',
    email: 'hyeyu@hanyang.ac.kr',
    phone: '',
    image: '/images/intro/professors/professors-04.webp',
  },
  {
    name: '이현주',
    position: '교수',
    major: '미술치료전공',
    email: 'lhjlhj529@hanyang.ac.kr',
    phone: '',
    image: '/images/intro/professors/professors-05.webp',
  },
  {
    name: '한영희',
    position: '교수',
    major: '예술치료전공',
    email: 'yhee711@hanyang.ac.kr',
    phone: '',
    image: '/images/intro/professors/professors-06.webp',
  },
  {
    name: '허성호',
    position: '교수',
    major: '심리학전공',
    email: 'powerrcy@hanyang.ac.kr',
    phone: '',
    image: '/images/intro/professors/professors-07.webp',
  },
] as const;
